# Makefile for the ByteBauble tests.


all: build_tests


build_tests:
	g++ -o api_test test/api_test.cpp src/bytebauble.cpp -I cpp/ -g3
	g++ -o varint_test test/varint_test.cpp src/bytebauble.cpp -I cpp/ -g3
	